<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prakashs-Laptop.local" failures="1" tests="12" name="org.testRunner.TestRunner" time="25.865" errors="0" timestamp="2025-08-15T19:18:33 IST" skipped="0">
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="2.609"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="0.975"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.628"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.270"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="11.034">
    <failure message="Success message not found within timeout." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Success message not found within timeout.
at org.stepdefinitions.UserRegistration.the_user_sees_confirmation_message(UserRegistration.java:106)
at âœ½.the user sees confirmation message "Your account was created successfully. You are now logged in."(file:///Users/prakashrajendran/git/repository-parabank_script/ParaBank/src/test/resources/FeatureFiles/register.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.208"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.564"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.057"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.064"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.256"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.108"/>
  <testcase classname="org.testRunner.TestRunner" name="runScenario" time="1.092"/>
</testsuite> <!-- org.testRunner.TestRunner -->
